spring.application.name=WealthPilot

# Server configuration
spring.datasource.url=jdbc:mysql://pixpay.tec.br/admin_testes
spring.datasource.username=admin_testes
spring.datasource.password=*fIE5bvKk5tpz2r&

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update